### PR TITLE
Pip install

### PR DESCRIPTION
**Pull request by jburel**
In this PR 
 * Make installable from pypi
 * Add readme
 * Add changelog, gitignore
 * Add travis file

The installation can be tested from testpypi:

``
pip install -i https://testpypi.python.org/pypi idr-py
``

cc @bramalingam

### CODE REVIEW

**Comment by jburel** [comment]
@bramalingam now green and pip installable

**Comment by bramalingam** [comment]
Looks good to merge, can start working on the code changes if this can be merged.

**Comment by bramalingam** [comment]
All 3 commits make sense. Happy with the changes.

**Comment by jburel** [comment]
Merging so @bramalingam can move forward with other changes

**Pull request merged**
