### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by manics**
Update idr-py for Python 3 only (setup.py metadata has been updated to indicate this)

To be fixed in the future:
- https://github.com/IDR/idr-py/issues/17

### CODE REVIEW

**Comment by manics** [comment]
Once this gets a dev tag I'll create a conda package.

**Comment by joshmoore** [comment]
At a quick glance, my primary question before a dev tag would be why the tests are disabled.

**Comment by manics** [comment]
They need IDR_XXX credentials which weren't public in the past.

**Comment by joshmoore** [comment]
Sorry, I see that was actually outwith this PR. :+1:

**Comment by jburel** [comment]
Dependencies are not installed when running 
``pip install git+https://github.com/manics/idr-py.git@python3``
e.g.
```
/opt/conda/envs/python3/lib/python3.6/site-packages/idr/connections.py in <module>
      6 import os
      7 
----> 8 import omero
      9 from omero.gateway import BlitzGateway
     10 

ModuleNotFoundError: No module named 'omero'
```
Discussed with @manics, changes to be pushed to make that possible

**Comment by jburel** [comment]
The last commit allows to install via pip 
It is now possible to access the dependencies

**Comment by jburel** [comment]
@manics you may want to adjust the version in setup.py This is currently 0.3.0

**Comment by manics** [comment]
Changed to `0.4.0.dev1`, and started a changelog

**Comment by jburel** [comment]
Ready to be tagged
@manics could you take care of it?

**Pull request merged**
